### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by kizule**
Travis and Scrutinizer aren't used/working at the moment, I've added GitHub Actions one (actually copied files from the SemanticMediaWiki/SemanticResultFormats repository).

### CODE REVIEW

**Comment by kizule** [comment]
@kghbln CI is here. 😄

**Comment by kizule** [comment]
@JeroenDeDauw Same question. :)

**Comment by krabina** [comment]
Checks have failed. Can you look into this, @kizule ?

**Comment by kizule** [comment]
> Checks have failed. Can you look into this, @kizule ?

Oh! Makefile is missing (https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/Makefile) and build/ should be copied from there as well.

Do you want to do it, or I should do it?

**Comment by krabina** [comment]
Please do it.

**Comment by gesinn-it-gea** [comment]
here's some README that might help: https://github.com/gesinn-it-pub/docker-compose-ci

**Comment by gesinn-it-gea** [comment]
Further plan is to include docs how to use the CI via a central "docs" repo and include this in all extensions using it.

**Pull request merged**
