### PR TITLE
SemanticCite MW1.39 / SWM 4.0.0 compatible

### PR DESCRIPTION
**Pull request by thomas-topway-it**
Ensures SemanticCite is compatible with MW1.39 / SWM 4.0.0

Fixes the following:

- remove reference to `$GLOBALS`
- replace deprecated global function `wfWikiID`
- remove obsolete `onoi/http-request`
- replace Title's `getNextRevisionID` / `getPreviousRevisionID` in `MediaWikiContextInteractor`
- replace deprecated global function `wfReadOnly`
- updates `MediaWikiContextInteractorTest`

### CODE REVIEW

**Comment by krabina** [comment]
Fixes #110

**Comment by kizule** [comment]
Can we get this merged please? :)

**Comment by krabina** [comment]
Did you try it out and can confirm it is working?
It is certainly working in our wikis.

**Comment by krabina** [comment]
@JeroenDeDauw I guess we need your help here. The PR seems to be working fine, but I don't know about the dependency topics also mentioned in #113

**Comment by krabina** [comment]
Oh. If I understand correctly this it more about making a new release so people don't have to use the dev-master, because #113 is solved already.

**Comment by JeroenDeDauw** [comment]
Indeed, you need a new release

**Comment by JeroenDeDauw** [comment]
Here is what to do: https://github.com/SemanticMediaWiki/SemanticCite/issues/118

**Pull request merged**
