### PR TITLE
Fix undefined constant warning

### LINKED ISSUE #107: Not compatible with SWM 4.0.0
### Setup and configuration

- SMW version: 4.0.0
- SCI version: master
- MW version: 1.35
- DB (MySQL etc. and version): MariaDB

### Issue

After upgrading to SMW 4.0.0 the SemanticCite extension no longer works. Annotations with [[CiteRef::CitationKey]] no longer render as expected, i.e. as a citation marker<sup>[1]</sup>, instead a link to the CitationKey page is shown.

### PR DESCRIPTION
**Pull request by kizule**
Fixes #107 completely.

### CODE REVIEW

**Comment by kizule** [comment]
DNM, I'm testing this patch. At this moment, it's showing notice that caching-related constants are already defined in MediaWiki's includes/Defines.php file.

**Comment by z929669** [comment]
Any confirmation yet if the "PHP Fatal error:  Uncaught Error: Undefined constant "CACHE_ANYTHING"" issue is resolved and 3.0 release status? Thanks in advance for all you guys are doing ;)

**Comment by tsadrafoundation** [comment]
When (SemanticCite ~3.0) installed through composer it will throw a dependency error, and packages will not be installed. For now I'm using the dev-master and manually changing `CACHE_EVERYTHING` to `-1` in `/var/www/html/extensions/SemanticCite/DefaultSettings.php`

**Comment by kizule** [comment]
I'm going to create a new PR.

**Pull request closed without merging**
